# Generated by Django 2.1.5 on 2019-01-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20160715_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('G', '✓ good'), ('E', '× error'), ('C', '~ running')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='story',
            name='content_type',
            field=models.CharField(blank=True, choices=[('T', 'text'), ('U', 'url'), ('I', 'image')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('O', 'Ok'), ('E', 'Error')], default='N', max_length=1),
        ),
    ]
