# Generated by Django 2.1.5 on 2019-01-09 09:04

from django.db import migrations

def remove_medium(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    try:
        medium = Service.objects.get(slug='medium')
        medium.delete()
    except Service.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20190109_0805'),
    ]

    operations = [
        migrations.RunPython(remove_medium),
    ]
